#=============================================================================
#
# file :        Makefile
#
# description : Include for the EigerFilewriter class.
#
# project :     Makefile to generate a Tango server
#
# $Author:  $
#
# $Revision: $
#
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#  		This file is generated by POGO
#	(Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#
MAKE_ENV = $(TANGO_DIR)/Libraries/cppserver/common
CLASS      = EigerFilewriter
MAJOR_VERS = 1
MINOR_VERS = 0
RELEASE    = Release_$(MAJOR_VERS)_$(MINOR_VERS)

#-----------------------------------------
#	 Install binary file
#-----------------------------------------
all:
	@echo "Nothing to do"

install:
	@echo "This class is used from EigerDectris. Nothing to install"

clean:
	@echo "Nothing to do"

include $(MAKE_ENV)/common_target.opt

#----------------------------------------------------
#	Tag the SVN module corresponding to this class
#----------------------------------------------------


tag:
ifeq ($(shell ls -d ../tags/$(RELEASE) 2>/dev/null ), ../tags/$(RELEASE))
	@echo $(RELEASE) exists, specify new version numbers
else
	svn copy ../trunk ../tags/$(RELEASE)
	svn commit ../tags/$(RELEASE) \
	-m "Tagging the $(RELEASE) of the $(CLASS) project."
endif
